# Generated by Django 4.1.7 on 2023-02-28 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='title',
        ),
    ]
